### ISSUE TITLE
great idea but...

### ISSUE THREAD

**Issue by fdncred** [Bdeering1/polykill#1]
This is a great idea but it's not really usable if you have a lot of folders. It scrolls over the top of my terminal and when you navigate with the up/down arrow you can't see what's going on. It would be great to put this in a fixed sized list based on the height of your terminal and then be able to scroll within that list.

**Comment by Bdeering1** [comment]
This is a great point and something I noticed but haven't gotten around to fixing yet. I'll try to get a fix out in the next few days. The temporary solution would be to only run the tool on smaller subdirectories (of course this assumes your projects are organized into subdirectories in the first place).

**Comment by Bdeering1** [comment]
Just pushed an update to fix this! Project results are now paginated.

**Comment by fdncred** [comment]
I can't seem to go to the next page. I'm on "Page 1 of 3" and neither the up/down arrows nor the pageup/pagedown keys will navigate to page 2. What's the magic keybinding?

**Comment by Bdeering1** [comment]
Left and right arrow keys!

Now that you mention it though I'll try to make that more clear, and I'll see about adding pageup/pagedown bindings as well.

**Comment by fdncred** [comment]
oh, left and right, I see now. Works great if you know that. LOL.  Thanks for your help!
